Add import by name for v2 ingest budgets
SumoLogic/terraform-provider-sumologic pull request #474
Opened 2023-01-20 19:48 UTC by ambrosy-eric

Allow importing v2 budget via name

### Issue related to

Related to [473](https://github.com/SumoLogic/terraform-provider-sumologic/issues/473)

2023-01-31 23:33 UTC, vsinghal13 reviewed
thanks, @ambrosy-eric for your contribution. Could you also add tests for the same?

2023-02-01 15:59 UTC, ambrosy-eric commented
Sure thing @vsinghal13 

Where would be a good place to add a test? Looking at `resource_sumologic_ingest_budget_v2_test.go` I see a warning not to modify the file
> //	This file is automatically generated by Sumo Logic and manual
> //	changes will be clobbered when the file is regenerated. Do not submit
> //	changes to this file.

2023-02-01 20:45 UTC, vsinghal13 commented
> Sure thing @vsinghal13
> 
> Where would be a good place to add a test? Looking at `resource_sumologic_ingest_budget_v2_test.go` I see a warning not to modify the file
> 
> > //	This file is automatically generated by Sumo Logic and manual
> > //	changes will be clobbered when the file is regenerated. Do not submit
> > //	changes to this file.

It's fine, you can add to the same file. We are not currently overriding these files.

2023-11-21 19:09 UTC, ambrosy-eric commented
sorry @vsinghal13 for the extremely log delay. Tried adding name import to the existing test. Lmk if that's acceptable

2025-03-24 14:56 UTC, ErikAtSumo commented
@ambrosy-eric I'm looking to clean up some old PRs. Is this a feature that you'd still like to add? If so, I'd be happy to help.

2025-03-26 14:34 UTC, ambrosy-eric commented
Heyo @ErikAtSumo (nice name 😄 ) yes i'd still be interested in getting this added.

2025-03-26 15:52 UTC, ErikAtSumo commented
@ambrosy-eric Sounds good. Would you please:

1. rebase on the latest master
2. update CHANGELOG.md

And I will review the code changes.

2025-03-26 16:09 UTC, ErikAtSumo requested changes

2025-03-26 16:09 UTC, ErikAtSumo commented on sumologic/sumologic_ingest_budget_v2.go
> +			return nil, nil
The calling code in `resourceSumologicIngestBudgetV2Import` doesn't handle this `nil, nil` case. If the body is `nil`, then it probably makes sense to return some kind of error:

```
if body == nil {
    return nil, fmt.Errorf("received empty response while searching for ingest budget '%s'", name)
}
```

2025-04-25 15:56 UTC, closed without merging

2025-04-25 15:56 UTC, ErikAtSumo commented
Merged these changes, plus the recommended fixes, in https://github.com/SumoLogic/terraform-provider-sumologic/pull/755